require 'savon'
require_relative 'csi_api/client_factory'
require_relative 'csi_api/csi_client'
require_relative 'csi_api/employee'
require_relative 'csi_api/member'
require_relative 'csi_api/mocks/savon_response'
require_relative 'csi_api/group_ex_class_list'
require_relative 'csi_api/group_ex_class'